![](https://info.grandcircus.co/hubfs/Grand%20Circus%20Logo-04.svg)
### Joe's Data Analysis - Day045 - 06/08/2023 - Weather Changes Over Time (Consuming APIs) (2 days)

### Import libraries

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns
import requests

In [7]:

!curl -o output.html www.grandcircus.co
#whget - doesn't appear to work - tyr this all on google colab.,

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0   1481      0 --:--:-- --:--:-- --:--:--  1528

In [11]:
url1 = "https://api.open-meteo.com/v1/forecast?latitude=44.98&longitude=-93.26&hourly=temperature_2m"
response = requests.get(url)
print(response.json())

{'latitude': 44.96949, 'longitude': -93.26297, 'generationtime_ms': 0.11599063873291016, 'utc_offset_seconds': 0, 'timezone': 'GMT', 'timezone_abbreviation': 'GMT', 'elevation': 254.0, 'hourly_units': {'time': 'iso8601', 'temperature_2m': '°C'}, 'hourly': {'time': ['2023-06-08T00:00', '2023-06-08T01:00', '2023-06-08T02:00', '2023-06-08T03:00', '2023-06-08T04:00', '2023-06-08T05:00', '2023-06-08T06:00', '2023-06-08T07:00', '2023-06-08T08:00', '2023-06-08T09:00', '2023-06-08T10:00', '2023-06-08T11:00', '2023-06-08T12:00', '2023-06-08T13:00', '2023-06-08T14:00', '2023-06-08T15:00', '2023-06-08T16:00', '2023-06-08T17:00', '2023-06-08T18:00', '2023-06-08T19:00', '2023-06-08T20:00', '2023-06-08T21:00', '2023-06-08T22:00', '2023-06-08T23:00', '2023-06-09T00:00', '2023-06-09T01:00', '2023-06-09T02:00', '2023-06-09T03:00', '2023-06-09T04:00', '2023-06-09T05:00', '2023-06-09T06:00', '2023-06-09T07:00', '2023-06-09T08:00', '2023-06-09T09:00', '2023-06-09T10:00', '2023-06-09T11:00', '2023-06-09T12:00', '2023-06-09T13:00', '2023-06-09T14:00', '2023-06-09T15:00', '2023-06-09T16:00', '2023-06-09T17:00', '2023-06-09T18:00', '2023-06-09T19:00', '2023-06-09T20:00', '2023-06-09T21:00', '2023-06-09T22:00', '2023-06-09T23:00', '2023-06-10T00:00', '2023-06-10T01:00', '2023-06-10T02:00', '2023-06-10T03:00', '2023-06-10T04:00', '2023-06-10T05:00', '2023-06-10T06:00', '2023-06-10T07:00', '2023-06-10T08:00', '2023-06-10T09:00', '2023-06-10T10:00', '2023-06-10T11:00', '2023-06-10T12:00', '2023-06-10T13:00', '2023-06-10T14:00', '2023-06-10T15:00', '2023-06-10T16:00', '2023-06-10T17:00', '2023-06-10T18:00', '2023-06-10T19:00', '2023-06-10T20:00', '2023-06-10T21:00', '2023-06-10T22:00', '2023-06-10T23:00', '2023-06-11T00:00', '2023-06-11T01:00', '2023-06-11T02:00', '2023-06-11T03:00', '2023-06-11T04:00', '2023-06-11T05:00', '2023-06-11T06:00', '2023-06-11T07:00', '2023-06-11T08:00', '2023-06-11T09:00', '2023-06-11T10:00', '2023-06-11T11:00', '2023-06-11T12:00', '2023-06-11T13:00', '2023-06-11T14:00', '2023-06-11T15:00', '2023-06-11T16:00', '2023-06-11T17:00', '2023-06-11T18:00', '2023-06-11T19:00', '2023-06-11T20:00', '2023-06-11T21:00', '2023-06-11T22:00', '2023-06-11T23:00', '2023-06-12T00:00', '2023-06-12T01:00', '2023-06-12T02:00', '2023-06-12T03:00', '2023-06-12T04:00', '2023-06-12T05:00', '2023-06-12T06:00', '2023-06-12T07:00', '2023-06-12T08:00', '2023-06-12T09:00', '2023-06-12T10:00', '2023-06-12T11:00', '2023-06-12T12:00', '2023-06-12T13:00', '2023-06-12T14:00', '2023-06-12T15:00', '2023-06-12T16:00', '2023-06-12T17:00', '2023-06-12T18:00', '2023-06-12T19:00', '2023-06-12T20:00', '2023-06-12T21:00', '2023-06-12T22:00', '2023-06-12T23:00', '2023-06-13T00:00', '2023-06-13T01:00', '2023-06-13T02:00', '2023-06-13T03:00', '2023-06-13T04:00', '2023-06-13T05:00', '2023-06-13T06:00', '2023-06-13T07:00', '2023-06-13T08:00', '2023-06-13T09:00', '2023-06-13T10:00', '2023-06-13T11:00', '2023-06-13T12:00', '2023-06-13T13:00', '2023-06-13T14:00', '2023-06-13T15:00', '2023-06-13T16:00', '2023-06-13T17:00', '2023-06-13T18:00', '2023-06-13T19:00', '2023-06-13T20:00', '2023-06-13T21:00', '2023-06-13T22:00', '2023-06-13T23:00', '2023-06-14T00:00', '2023-06-14T01:00', '2023-06-14T02:00', '2023-06-14T03:00', '2023-06-14T04:00', '2023-06-14T05:00', '2023-06-14T06:00', '2023-06-14T07:00', '2023-06-14T08:00', '2023-06-14T09:00', '2023-06-14T10:00', '2023-06-14T11:00', '2023-06-14T12:00', '2023-06-14T13:00', '2023-06-14T14:00', '2023-06-14T15:00', '2023-06-14T16:00', '2023-06-14T17:00', '2023-06-14T18:00', '2023-06-14T19:00', '2023-06-14T20:00', '2023-06-14T21:00', '2023-06-14T22:00', '2023-06-14T23:00'], 'temperature_2m': [26.2, 24.1, 23.7, 23.4, 22.9, 21.5, 21.2, 20.7, 19.9, 19.2, 17.3, 16.3, 16.8, 18.1, 20.2, 21.6, 23.5, 24.5, 26.0, 26.9, 27.4, 27.9, 27.2, 26.8, 26.2, 25.1, 22.8, 21.1, 19.8, 18.7, 17.9, 17.0, 16.2, 15.4, 14.6, 14.5, 16.9, 19.6, 22.1, 24.8, 26.7, 27.9, 28.8, 29.2, 29.6, 29.1, 28.6, 28.6, 28.3, 27.3, 25.1, 23.6, 22.3, 21.3, 20.3, 20.0, 19.4, 19.0, 18.8, 18.6, 20.6, 23.1, 25.9, 27.4, 27.8, 23.4, 19.9, 22.6, 21.7, 20.9, 19.8, 18.4, 18.2, 18.0, 17.7, 17.4, 17.3, 16.9, 16.2, 15.7, 15.4, 14.5, 14.7, 14.0, 13.3, 13.5, 15.7, 18.5, 20.0, 21.0, 21.6, 21.9, 22.2, 22.3, 22.0, 21.2, 20.4, 19.0, 17.3, 16.1, 15.2, 14.4, 13.6, 12.9, 12.2, 11.6, 11.2, 10.9, 11.7, 13.5, 15.5, 17.4, 18.8, 20.1, 21.2, 22.2, 22.6, 22.8, 22.7, 21.7, 21.0, 20.2, 18.6, 18.2, 17.5, 16.8, 16.3, 15.7, 15.2, 15.1, 14.8, 15.1, 16.1, 17.5, 19.3, 21.0, 22.5, 24.0, 25.1, 26.0, 26.6, 26.9, 26.8, 26.3, 25.6, 24.6, 23.2, 22.0, 21.1, 20.3, 19.5, 18.8, 18.1, 17.7, 17.5, 17.4, 18.0, 19.7, 21.9, 24.0, 25.7, 27.1, 28.2, 28.9, 29.2, 29.2, 28.9, 28.3]}}

In [12]:
if response.status_code == 200:
    #   Parse the data into a json object
    data = response.json()
    
    # convert the JSON to a pandas dataframe...
    df = pd.DataFrame(data)
    
else:
    print("ERROR: ", response.status_code)

In [13]:
df.head()

,latitude,longitude,generationtime_ms,utc_offset_seconds,timezone,timezone_abbreviation,elevation,hourly_units,hourly
time,44.96949,-93.26297,0.115991,0,GMT,GMT,254.0,iso8601,"[2023-06-08T00:00, 2023-06-08T01:00, 2023-06-0..."
temperature_2m,44.96949,-93.26297,0.115991,0,GMT,GMT,254.0,°C,"[26.2, 24.1, 23.7, 23.4, 22.9, 21.5, 21.2, 20...."

In [15]:
url2 = "https://api.open-meteo.com/v1/forecast?latitude=44.98&longitude=-93.26&hourly=temperature_2m&forecast_days=1"
response2 = requests.get(url2)
print(response2.json())
if response2.status_code == 200:
    #   Parse the data into a json object
    data2 = response.json()
    
    # convert the JSON to a pandas dataframe...
    df2 = pd.DataFrame(data2)
    
else:
    print("ERROR: ", response2.status_code)

{'latitude': 44.96949, 'longitude': -93.26297, 'generationtime_ms': 0.14102458953857422, 'utc_offset_seconds': 0, 'timezone': 'GMT', 'timezone_abbreviation': 'GMT', 'elevation': 254.0, 'hourly_units': {'time': 'iso8601', 'temperature_2m': '°C'}, 'hourly': {'time': ['2023-06-08T00:00', '2023-06-08T01:00', '2023-06-08T02:00', '2023-06-08T03:00', '2023-06-08T04:00', '2023-06-08T05:00', '2023-06-08T06:00', '2023-06-08T07:00', '2023-06-08T08:00', '2023-06-08T09:00', '2023-06-08T10:00', '2023-06-08T11:00', '2023-06-08T12:00', '2023-06-08T13:00', '2023-06-08T14:00', '2023-06-08T15:00', '2023-06-08T16:00', '2023-06-08T17:00', '2023-06-08T18:00', '2023-06-08T19:00', '2023-06-08T20:00', '2023-06-08T21:00', '2023-06-08T22:00', '2023-06-08T23:00'], 'temperature_2m': [26.2, 24.1, 23.7, 23.4, 22.9, 21.5, 21.2, 20.7, 19.9, 19.2, 17.3, 16.3, 16.8, 18.1, 20.2, 21.6, 23.5, 24.5, 26.0, 26.9, 27.4, 27.9, 27.2, 26.8]}}

In [16]:
df2.loc['time', 'hourly']

['2023-06-08T00:00',
 '2023-06-08T01:00',
 '2023-06-08T02:00',
 '2023-06-08T03:00',
 '2023-06-08T04:00',
 '2023-06-08T05:00',
 '2023-06-08T06:00',
 '2023-06-08T07:00',
 '2023-06-08T08:00',
 '2023-06-08T09:00',
 '2023-06-08T10:00',
 '2023-06-08T11:00',
 '2023-06-08T12:00',
 '2023-06-08T13:00',
 '2023-06-08T14:00',
 '2023-06-08T15:00',
 '2023-06-08T16:00',
 '2023-06-08T17:00',
 '2023-06-08T18:00',
 '2023-06-08T19:00',
 '2023-06-08T20:00',
 '2023-06-08T21:00',
 '2023-06-08T22:00',
 '2023-06-08T23:00',
 '2023-06-09T00:00',
 '2023-06-09T01:00',
 '2023-06-09T02:00',
 '2023-06-09T03:00',
 '2023-06-09T04:00',
 '2023-06-09T05:00',
 '2023-06-09T06:00',
 '2023-06-09T07:00',
 '2023-06-09T08:00',
 '2023-06-09T09:00',
 '2023-06-09T10:00',
 '2023-06-09T11:00',
 '2023-06-09T12:00',
 '2023-06-09T13:00',
 '2023-06-09T14:00',
 '2023-06-09T15:00',
 '2023-06-09T16:00',
 '2023-06-09T17:00',
 '2023-06-09T18:00',
 '2023-06-09T19:00',
 '2023-06-09T20:00',
 '2023-06-09T21:00',
 '2023-06-09T22:00',
 '2023-06-09T23:00',
 '2023-06-10T00:00',
 '2023-06-10T01:00',
 '2023-06-10T02:00',
 '2023-06-10T03:00',
 '2023-06-10T04:00',
 '2023-06-10T05:00',
 '2023-06-10T06:00',
 '2023-06-10T07:00',
 '2023-06-10T08:00',
 '2023-06-10T09:00',
 '2023-06-10T10:00',
 '2023-06-10T11:00',
 '2023-06-10T12:00',
 '2023-06-10T13:00',
 '2023-06-10T14:00',
 '2023-06-10T15:00',
 '2023-06-10T16:00',
 '2023-06-10T17:00',
 '2023-06-10T18:00',
 '2023-06-10T19:00',
 '2023-06-10T20:00',
 '2023-06-10T21:00',
 '2023-06-10T22:00',
 '2023-06-10T23:00',
 '2023-06-11T00:00',
 '2023-06-11T01:00',
 '2023-06-11T02:00',
 '2023-06-11T03:00',
 '2023-06-11T04:00',
 '2023-06-11T05:00',
 '2023-06-11T06:00',
 '2023-06-11T07:00',
 '2023-06-11T08:00',
 '2023-06-11T09:00',
 '2023-06-11T10:00',
 '2023-06-11T11:00',
 '2023-06-11T12:00',
 '2023-06-11T13:00',
 '2023-06-11T14:00',
 '2023-06-11T15:00',
 '2023-06-11T16:00',
 '2023-06-11T17:00',
 '2023-06-11T18:00',
 '2023-06-11T19:00',
 '2023-06-11T20:00',
 '2023-06-11T21:00',
 '2023-06-11T22:00',
 '2023-06-11T23:00',
 '2023-06-12T00:00',
 '2023-06-12T01:00',
 '2023-06-12T02:00',
 '2023-06-12T03:00',
 '2023-06-12T04:00',
 '2023-06-12T05:00',
 '2023-06-12T06:00',
 '2023-06-12T07:00',
 '2023-06-12T08:00',
 '2023-06-12T09:00',
 '2023-06-12T10:00',
 '2023-06-12T11:00',
 '2023-06-12T12:00',
 '2023-06-12T13:00',
 '2023-06-12T14:00',
 '2023-06-12T15:00',
 '2023-06-12T16:00',
 '2023-06-12T17:00',
 '2023-06-12T18:00',
 '2023-06-12T19:00',
 '2023-06-12T20:00',
 '2023-06-12T21:00',
 '2023-06-12T22:00',
 '2023-06-12T23:00',
 '2023-06-13T00:00',
 '2023-06-13T01:00',
 '2023-06-13T02:00',
 '2023-06-13T03:00',
 '2023-06-13T04:00',
 '2023-06-13T05:00',
 '2023-06-13T06:00',
 '2023-06-13T07:00',
 '2023-06-13T08:00',
 '2023-06-13T09:00',
 '2023-06-13T10:00',
 '2023-06-13T11:00',
 '2023-06-13T12:00',
 '2023-06-13T13:00',
 '2023-06-13T14:00',
 '2023-06-13T15:00',
 '2023-06-13T16:00',
 '2023-06-13T17:00',
 '2023-06-13T18:00',
 '2023-06-13T19:00',
 '2023-06-13T20:00',
 '2023-06-13T21:00',
 '2023-06-13T22:00',
 '2023-06-13T23:00',
 '2023-06-14T00:00',
 '2023-06-14T01:00',
 '2023-06-14T02:00',
 '2023-06-14T03:00',
 '2023-06-14T04:00',
 '2023-06-14T05:00',
 '2023-06-14T06:00',
 '2023-06-14T07:00',
 '2023-06-14T08:00',
 '2023-06-14T09:00',
 '2023-06-14T10:00',
 '2023-06-14T11:00',
 '2023-06-14T12:00',
 '2023-06-14T13:00',
 '2023-06-14T14:00',
 '2023-06-14T15:00',
 '2023-06-14T16:00',
 '2023-06-14T17:00',
 '2023-06-14T18:00',
 '2023-06-14T19:00',
 '2023-06-14T20:00',
 '2023-06-14T21:00',
 '2023-06-14T22:00',
 '2023-06-14T23:00']

### Jason's example notebook: https://drive.google.com/file/d/17e90aHSMzYIXnItpwC-ehlLp6HwEDJQb/edit